### ISSUE TITLE
Research visualisation technologies

### ISSUE THREAD

**Issue by simonstadlinger** [hpi-swa-lab/BP2019RH1#2]
### Librarys

- [x] ChartJS
- [x] D3JS
- [x] Vega - Lite
- [ ] ProcessingJS
- [ ] VisJS
- [x] ThreeJS
- [ ] Echarts & Highcharts
- [ ] Metric-Graphics
- [ ] Recharts
- [x] D3js
- [x] React-Vis
- [x] CartoDB
- [x] ggPlot2
- [ ] matPlotLib
- [x] Raw Graphs
- [x] C3js
- [x] tauCharts

### Others

- [ ] Tableu
- [ ] Excel
- [ ] PowerBI
- [ ] Visualizer
- [ ] GraphViz

**Comment by leowe** [comment]
Currently we are focusing on d3.js
