### ISSUE TITLE
Create interactive data visualization

### ISSUE THREAD

**Issue by m0e33** [hpi-swa-lab/BP2019RH1#4]
AC: 
1. a Table with real data and can be seen
2. visualization can be plotted out of data
3. when clicking on a data in the chart, the cell responsible for the data point will be highlighted
4. when clicking on table cell corresponding visualization data point is highlighted

**Comment by leowe** [comment]
One solution can be found here: https://lively-kernel.org/lively4/lively4-bp2019/start.html?load=https://lively-kernel.org/lively4/BP2019RH1/doc/research-provenance/d3FromVis2Data.md
