### ISSUE TITLE
Write script to compress data

### ISSUE THREAD

**Issue by leowe** [hpi-swa-lab/BP2019RH1#44]
AC: 
- [x] Converts jsonl data we got from Luke to slimmed down json / csv file, which includes all the data points which we need (age, gender, including themes)
- [x] looks themes / keys up in GitHub repo to determine which keys to keep
- [x] Allow many key urls to be used for one compression
- [x] store compressed data on server so it does not have to be build on every request
- [x] Write documentation

https://lively-kernel.org/voices/parsing-data/

**Comment by LucPrestin** [comment]
Documentation can be found here: https://lively-kernel.org/voices/parsing-data/parsing.md
